# Generated by Django 2.0.3 on 2019-04-10 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('talker1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talker1', to=settings.AUTH_USER_MODEL)),
                ('talker2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talker2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField(max_length=2000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='None', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=6)),
                ('intro', models.CharField(default='None', max_length=200)),
                ('profile', imagekit.models.fields.ProcessedImageField(default='user/img/default.jpg', upload_to='user/img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
