# Generated by Django 2.0.3 on 2019-04-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
