# Generated by Django 2.0.3 on 2019-04-15 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190411_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='talker1',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='talker2',
        ),
        migrations.RemoveField(
            model_name='message',
            name='belong_to',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chatroom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
