# Generated by Django 2.0.3 on 2019-04-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190417_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='qq',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
