# Generated by Django 2.0.3 on 2019-04-21 19:20

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190417_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='stuCardPhoto',
            field=imagekit.models.fields.ProcessedImageField(default=None, upload_to='user/img/verify'),
        ),
    ]
