# Generated by Django 2.0.3 on 2019-04-21 19:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190421_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='stuCardPhoto',
            field=imagekit.models.fields.ProcessedImageField(default='user/img/default.jpg', upload_to='user/img/verify'),
        ),
    ]
