# Generated by Django 2.0.3 on 2019-04-21 19:27

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190421_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='stuCardPhoto',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='user/img/verify'),
        ),
    ]
