# Generated by Django 2.0.3 on 2019-04-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='is_verify',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='message',
            name='id_content',
            field=models.IntegerField(default=0),
        ),
    ]
