# Generated by Django 2.0.3 on 2019-04-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190423_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('M', 'massage'), ('S', 'stu_verify'), ('C', 'commodity_verify')], default='message', max_length=20),
        ),
    ]
