# Generated by Django 2.1.4 on 2019-05-14 12:23

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', DjangoUeditor.models.UEditorField(blank=True, verbose_name='commodity_descriprion')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('for_sale', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='CommoditySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CommodityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='commodity_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_source', to='commodity.CommoditySource'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='commodity_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_tag', to='commodity.CommodityTag'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity', to=settings.AUTH_USER_MODEL),
        ),
    ]
