# Generated by Django 2.1.4 on 2019-04-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='if_varified',
            field=models.BooleanField(default=True),
        ),
    ]
