# Generated by Django 2.1.4 on 2019-04-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
