# Generated by Django 2.1.4 on 2019-04-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_commodity_if_varified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='if_varified',
        ),
        migrations.AddField(
            model_name='commodity',
            name='is_varified',
            field=models.BooleanField(default=True),
        ),
    ]
