# Generated by Django 2.1.4 on 2019-04-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_auto_20190423_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
