# Generated by Django 2.1.4 on 2019-04-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0006_commodity_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
