# Generated by Django 2.1.4 on 2019-04-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0010_auto_20190415_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommoditySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=300)),
            ],
        ),
    ]
