# Generated by Django 2.1.4 on 2019-04-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0011_commoditysource'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='commodity_source',
            field=models.ManyToManyField(related_name='commodity_source', to='commodity.CommoditySource'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodity_tag',
            field=models.ManyToManyField(related_name='commodity_tag', to='commodity.CommodityTag'),
        ),
    ]
