# Generated by Django 2.1.4 on 2019-04-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0012_auto_20190415_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='author',
            new_name='owner',
        ),
    ]
