# Generated by Django 2.1.4 on 2019-04-18 10:35

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0013_auto_20190417_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='body',
            field=DjangoUeditor.models.UEditorField(verbose_name='commodity_descrption'),
        ),
    ]
