# Generated by Django 2.1.4 on 2019-04-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0014_auto_20190418_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='body',
            field=models.TextField(),
        ),
    ]
