# Generated by Django 2.1.4 on 2019-04-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0016_auto_20190418_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='body',
            field=models.TextField(),
        ),
    ]
