# Generated by Django 2.1.4 on 2019-04-18 14:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0017_auto_20190418_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
