# Generated by Django 2.1.4 on 2019-04-18 14:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0019_auto_20190418_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='commodity_description'),
        ),
    ]
