# Generated by Django 2.1.4 on 2019-04-18 14:57

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0020_auto_20190418_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='body',
            field=DjangoUeditor.models.UEditorField(verbose_name='commodity_descriprion'),
        ),
    ]
