# Generated by Django 2.0.3 on 2019-04-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='mem1_del',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='mem2_del',
            field=models.BooleanField(default=False),
        ),
    ]
