# Generated by Django 2.0.3 on 2019-04-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_auto_20190420_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='mem1_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='mem2_read',
            field=models.BooleanField(default=False),
        ),
    ]
